### ISSUE TITLE
Secure file deletion

### ISSUE THREAD

**Issue by kzshantonu** [vwxyzjn/portwarden#2]
I propose adding a secure file deletion of the sensitive files after zipping and encrypting and/or an optional command flag to keep the files intact so we can review them and securely delete them ourselves. Regards and cheers

**Comment by vwxyzjn** [comment]
Hello @kzshantonu, thanks for raising this issue. I am thinking maybe something mentioned in here: https://www.socketloop.com/tutorials/golang-secure-file-deletion-with-wipe-example can be implemented.

Though I may have time to do it during my refactor in the upcoming months, this feature really is currently not of my priority... If you have experience with Go, your PR would be more than welcomed.
