### ISSUE TITLE
mac failed: when trying to make query to bw cli

### ISSUE THREAD

**Issue by RakibFiha** [vwxyzjn/portwarden#22]
Can anyone help me, I am having the following issue with bw-cli.
Whenever I try to make any kind of query or request to bw cli I keep getting this mac failed error. I am using Ubuntu 18.04
```
💲 bw get password namep --session $session
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
123456
````
Exit status:
```
💲 echo $?
0
```
Current version:
```
💲 bw -v
1.7.4
```

**Comment by vwxyzjn** [comment]
Hey this is more of a Bitwarden CLI issue. You should try to post it in their forum.

Costa

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by RakibFiha** [comment]
I just realised that I am in the wrong forum
