### ISSUE TITLE
You are not logged in.encryption failed

### ISSUE THREAD

**Issue by sutidor** [vwxyzjn/portwarden#24]
With the latest version of bw.exe portwarden fails. I need to download 2018 Version of Bitwarden's bw.exe. Is this project still alive? (great project!)

**Comment by vwxyzjn** [comment]
Hi,

I am a little swarmed by work now, but I set a reminder to work on it this weekend. I intend to also add restore functionality.

Costa

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vwxyzjn** [comment]
Fixed. See the latest release
