### ISSUE TITLE
Confused about how to install portwarden

### ISSUE THREAD

**Issue by zadrafi** [vwxyzjn/portwarden#25]
Hi, 

I installed the BW cli and that was pretty smooth but pretty confused about how to install portwarden. I use a mac

**Comment by vwxyzjn** [comment]
Hi, open a terminal in the folder where you downloaded the executable, and then run

./portwarden

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zadrafi** [comment]
Appreciate the quick response! Still a bit confused about which part of the release I should download? Was looking for macOS but only see versions for linux and windows. Excuse the ignorance (not used to doing stuff like this)

**Comment by vwxyzjn** [comment]
No problem at all. I believe you are looking for keyword darwin.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zadrafi** [comment]
Thanks, I wonder if I'm missing something? did what you asked, downloaded  portwarden_darwin_amd64 and then set the terminal to my downloads folder and ran ./portwarden but keep encountering "./portwarden: command not found"

**Comment by vwxyzjn** [comment]
Change the file name from portwarden_darwin_amd64 to portwarden :). Let me know if it works

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zadrafi** [comment]
Yep did that and still encountering the same error in the terminal. Do I need to have any other components installed? I use homebrew

**Comment by vwxyzjn** [comment]
You shouldn’t need anything else. Perhaps you could record a gif of what you are doing? And it would be helpful if you can show me your error. A screenshot.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zadrafi** [comment]
Ah Okay. I figured it out. It was saved as a .txt file but needed to be opened with a terminal and registered as a terminal file. Following steps worked for me 

1

    Go to your Terminal or iTerm.

    Change to directory where your file is located.

    Type the following:

    chmod a+x (portwarden)

    Right click on your file and select Open with and Other.

    Enable All Applications and choose Terminal.

    NOTE: If you always want to open that file with Terminal, then check Always Open With.

    Finally, double click on your file and it should work.

**Comment by vwxyzjn** [comment]
Oh sorry I forgot to remind you that you should do

chmod +x ./portwarden

Could you successfully create a backup?


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zadrafi** [comment]
currently running ./portwarden --passphrase 1234 --filename backup.portwarden encrypt
though it seems to be taking a while to give me the email and password prompt

**Comment by zadrafi** [comment]
ah okay looks like it worked! I just logged out of the bw CLI and didn't log back in and started portwarden which finally gave me the promot

**Comment by zadrafi** [comment]
bought you a coffee! thanks for all your help and work!

**Comment by vwxyzjn** [comment]
My pleasure. Glad it worked for you :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
