### ISSUE TITLE
Compatability w/ Bitwarden_rs

### ISSUE THREAD

**Issue by feerlessleadr** [vwxyzjn/portwarden#28]
Hi - is this program able to backup from bitwarden proper and then restore to bitwarden_rs?

Apologies, I'm not really sure where to post a question, and I don't see this covered in the readme. thanks

**Comment by vwxyzjn** [comment]
I am pretty sure you can.

Costa
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by feerlessleadr** [comment]
Thanks - I'll give it a shot and report back.

**Comment by feerlessleadr** [comment]
Just to close the loop on this, migrating from bitwarden to bitwarden_rs with portwarden worked flawlessly. Thanks
