### ISSUE TITLE
Scheduled backup?

### ISSUE THREAD

**Issue by onnyyonn** [vwxyzjn/portwarden#29]
The description of this repository says "Create (Scheduled) Encrypted Backups". But from the documentation, it doesn't seem to have an option for scheduling backups. Is there something I am missing?

**Comment by vwxyzjn** [comment]
Hi
That was there for legacy reasons. If you want to do scheduled back ups, try Cron job

Costa

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
