### ISSUE TITLE
Support for passphrases with spaces

### ISSUE THREAD

**Issue by x49QK2S25Jv** [vwxyzjn/portwarden#30]
Any chance it could support passphrases with spaces?

**Comment by vwxyzjn** [comment]
Hi, is there a compelling reason for the support?
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by x49QK2S25Jv** [comment]
I've got one or more spaces in my passphrase

**Comment by vwxyzjn** [comment]
For now, I would suggest using a pass phrase without spaces. Introducing spaces to pass phrases might make the implementation a little tricky (could introduce bugs), so I am a little reserved for adding this new feature. 

Of course, PR is always welcome.
