### ISSUE TITLE
Fails on secure note with slash / in the name

### ISSUE THREAD

**Issue by alexhk** [vwxyzjn/portwarden#31]
I have a note that's named "drive mount on NUC / ASUS SSD" with an attachment (.encfs6.xml) and it fails to complete (no error). It seems the culprit is the name, as it creates a folder "drive mount on NUC" with a subfolder "ASUS SSD" but it never completes the backup. This is true for version 1.0.0 as well as for version 0 from when you released it first.

Alex

**Comment by vwxyzjn** [comment]
Hi, by default `portwarden` Download attachments and save them to folders. So `drive mount on NUC / ASUS SSD` is not a valid folder name. Maybe for the next release I will fix it, but currently please just avoid `/` in the note’s name.
