### ISSUE TITLE
Unable to encrypt and create a .portwarden file.

### ISSUE THREAD

**Issue by GoldFury** [vwxyzjn/portwarden#32]
Hey there,

I've followed all the steps required to run Portwarden but I seem to be stuck on the part where I'm supposed to encrypt the vault.
Basically, when I type in, for example, "portwarden --passphrase 1234 --filename backup.portwarden encrypt", nothing happens.
If I press ENTER two times, this shows up on my screen:
? Master password: [input is hidden] [37D[37C[2K[G? Master password: [hidden][27D[27C
Invalid master password.
I've tried numerous times and it worked for me once, but it didn't create the backup.portwarden file.
I figured that Portwarden could not create a file due to it being in the Program File x86 folder, therefore I moved it to the Documents folder but it didn't work, it kept giving me the error above.

**EDIT:** I managed to get it working, all I had to do was logout of BW by using bw logout then use Portwarden; Now, though, there's another problem, I cannot find the exported file anywhere. It's not in the folder where Portwarden is, it's not on the Desktop, it's not in the directory of bw.exe. 

**EDIT 2:** I had set the folder where the portwarden.exe is located as a PATH in the system variables, hence why it didn't create a .portwarden file, which should have went into the System32.
I looked into the System32 folder and I haven't found the file, probably due to the access being denied, therefore I set my cd to the folder where Portwarden is located and lo and behold, the file was created successfully.
Have a coffee.

**Comment by vwxyzjn** [comment]
Hi thanks for the bug report. One thing you could try is to put `portwarden.exe` in a desired folder, open a terminal at the folder, and run `./portwarden.exe --passphrase 1234 --filename backup.portwarden encrypt`. I think this should work. Let me know how it goes. 

Thanks for the coffee.

**Comment by vwxyzjn** [comment]
Please reopen the issue if it is still a problem
