### ISSUE TITLE
Export fails with [object Object] and timestamp

### ISSUE THREAD

**Issue by edupr91** [vwxyzjn/portwarden#35]
Hi, as you can see in the example portwarden fails while trying to run an export...

```
[dude@host01 bitwarden]$ /usr/bin/portwarden --passphrase 1234 --filename backup.portwarden encrypt
? Email address: root@domain.com
? Master password: [hidden]
[object Object]
2021/11/04 08:18:04 
[dude@host01 bitwarden]$ echo $?
1
[dude@host01 bitwarden]$ md5sum /usr/bin/portwarden
841c0fa40a8364a99767fc0454ca84ac  /usr/bin/portwarden
[dude@host01 bitwarden]$ /usr/bin/portwarden --version 
portwarden version 1.0.0

```

We are currently using RHEL7.9  and using the last portwarden version...
The error is not descriptive at all. it only asks us for the email and master password. We have set up 2fact authentication but it doesn't arrive to ask us for the code.

**Comment by mxve** [comment]
What version of [bitwarden cli](https://github.com/bitwarden/cli/releases) are you using?
Recently Bitwarden started requiring captchas (or api keys on cli), so you might have to update bitwarden.

**Comment by edupr91** [comment]
Yes!!, that was the main problem.
I had 1.11.0. I just had to update to the last one on npm (1.19.1) and everything started working again. 

Thanks a lot.

**Comment by vwxyzjn** [comment]
@mxve thanks for checking into this and help @edupr91
