### ISSUE TITLE
Cannot create backup. Maybe cause of Yubikey?

### ISSUE THREAD

**Issue by henningBunk** [vwxyzjn/portwarden#42]
Hi there.
I am getting the error

> No providers available for this client.

I think this is because of me using a Yubikey for 2FA.

I found that there should be a method to use the yubikey somehow: https://github.com/vwxyzjn/portwarden/blob/69a0337bbf844078eed3b8ce82fd2d0d0cd7afdb/core.go#L55

But I don't know how to set method to the yubikey value. Can anyone help?

Alternativly, it would be great if one could login with an API client id and API key, this certainly does work with a YubiKey. Is there a way to do this?

**Comment by vwxyzjn** [comment]
Try set up another 2FA like authenticator.

**Comment by henningBunk** [comment]
I would like to keep my Yubikey as an exclusive 2FA. And I am also too lazy to add and remove 2FA methods each time I make a backup 😄.
I did wrote a small [Python script](https://github.com/henningBunk/bitwarden-dl) which uses api tokens. So if you don't think this is something you want for portwarden please feel free to close this ticket.

**Comment by vwxyzjn** [comment]
Yeah I understand. Sorry won't have the bandwidth to work on this.
